osx_image: mavericks
env: RUBY=ruby-head
language: objective-c
install: curl -L https://get.smf.sh | sh
before_script:
  - export PATH="$HOME/.sm/bin:$HOME/.sm/pkg/active/bin:$PATH"
  - export rvm_git_clone_depth=1
  - rvm get head
  - rvm autolibs smf
  - sudo mkdir -p /etc/openssl
  - "sudo chown -R $USER: /etc/openssl"
  - rvm remove $RUBY
script: rvm install $RUBY --movable
after_success:
  - rvm use $RUBY
  - ruby -v
  - ruby -ropenssl -ryaml -ropen-uri -e 'puts(open("https://google.com").each_line.first.to_yaml)'
  - ruby -ryaml -e 'puts Psych::LIBYAML_VERSION'
  - rvm prepare $RUBY
after_failure:
  - find $rvm_path/log/ -type f | xargs ls -t | head -n 1 | xargs cat
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
  email:
    recipients:
      - mpapis@gmail.com
    on_failure: change
